### PR TITLE
Added ROT to DB and repaired xml file.

### PR DESCRIPTION
**Pull request by neil-d95**

### CODE REVIEW

**Comment by birkelbach** [comment]
The default location for $FG_ROOT in the current version of FlightGear is /usr/share/games/flightgear/ according to the Wiki.  I think we should keep this as the default.

Also removing the <factor> attribute will cause the database entry to be written in ft/sec^2.  This is not correct.  The FIX-Gateway database expects this information to be in G's.  The reason for the <factor> attribute is to make this correction.

**Comment by neil-d95** [comment]
Phil,

So I've got no problem with the FG_ROOT.

     We should keep the factoring out until it's is verified corrected 
in converting from Ft/sec^2 to g. I was getting values too low to be 
useful 0.0001g then with a hard rudder input. That doesn't jive. I did 
test with removal of the conversion in the code. This is currently 
working, and tested with max deflection I only problem is it is way 
sensitive. I'm 80% sure it is coming from Flight Gear .

**Comment by birkelbach** [comment]
I have checked several sources and all agree that 0.0310809 is the conversion factor from ft/sec/sec to G.  This does not need verification.  If FlightGear is not sending the correct information then that is another issue.  But, I've been watching the accelerations on FG with the Slip/Skid ball and they seem to agree with what I would expect.  I get about 2 ft/sec^2 of acceleration with about a ball of deflection.  This converted to G with the above factor would be around 0.06 which is pretty close to what I would expect.  I also see the correct value in FIX-Gateway.

**Comment by neil-d95** [comment]
that wasn't in the conversion factor I saw when I changed it was 9.8 
which after I looked was Meter/sec2 if you want to kick it go ahead.

**Comment by birkelbach** [comment]
I'll pull the latest pyEfis and see what the deal is.  Maybe your version of FlightGear is not producing the numbers correctly.  I have 2018.3.1 which I don't think is the latest but it's pretty close.  I'll let you know what I find.

**Comment by birkelbach** [comment]
Not merged.  ROT changes were made in PR #66

**Pull request closed without merging**
