### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jmg22**
hello i just to add some plugins to fixgw

-bmp085
-bno055
-button
-mcp3008
-rotary_encoder
-virtualwire

this is working but not finish.

a cleanup and some errors handling need to be done

### CODE REVIEW

**Comment by birkelbach** [comment]
I pulled this into my local branch to take a look at it.  I made a few changes (just some merge conflicts) and pushed them into a new develop branch.  I do have some comments...

This breaks Python 3 compatibility.  It seems mostly tab/space issues at the moment, we should probably fix this before merging into the master branch.

Also it seems to me that the AeroCalc library should just be a dependency instead of being included in the source.  Pip doesn't work with this library.  Maybe we can get Kevin to fix that or we can fork it and get it working ourselves.

I think it also makes sense to prefix the names of the Raspberry Pi dependent modules with "rpi_" or something similar.  There is no requirement that this program run on a RPi.

Thanks for the good work Jean.

**Comment by birkelbach** [comment]
Aerocalc installs with the setup.py file that comes in the distribution and it imports.  I haven't tried any functions but it worked fine on my virtualenv with Python 2 and 3 so it's probably okay other than not being on pip.  It installs easy enough.  I couldn't find anywhere in this pull where it was being used anyway.

I'm not sure what were the issues with the new plugins.  I tried to load them and got a bunch of errors about mixing tabs and spaces.  Loaded them in Python 2 and they worked except for me not having any of the other modules that were needed.  Didn't go any further than that.  I won't be able to get them to load anyway because I'm out of town and not near my Raspberry Pi so I don't think the libraries that are required will load and work anyway.

**Comment by neil-d95** [comment]
Sounds like the formatting is wrong with those errors. I'll pull the develop and try to go through it.

Neil

**Comment by jmg22** [comment]
Hello,

i don’t use Aerocalc yet, i just put in fixgw for testing but honestly i think pyEfis is a better place. Unicode plain text give me some trouble (UTF-8), i’m working with a macbook with file sharing from the raspberry pi and i think this is maybe a problem for python( some time i need to use console with nano to adjust the tab). 

« I think it also makes sense to prefix the names of the Raspberry Pi dependent modules with "rpi_" or something similar. There is no requirement that this program run on a RPi. » yes you are right, i will do.

sorry for my bad english and thank you for your great work

Jean-Manuel Gagnon

**Pull request closed without merging**
