### PR TITLE
Add DB mappings to more completely feed the EFIS display.

### PR DESCRIPTION
**Pull request by Maker42**

### CODE REVIEW

**Comment by birkelbach** [comment]
Doesn't that need to be FUELQ1?

**Comment by Maker42** [comment]
You'd think that. I sure did until I saw it didn't work. Having not closely
examined key mappings and behaviors, I couldn't explain why.

**Comment by birkelbach** [comment]
Okay.  I'm gonna go ahead and merge the changes, and then figure out why we have that discrepancy.  I don't like that mapping method anyway.  I'm probably going to change it to a configuration file of some kind.

**Comment by Maker42** [comment]
Yes, I agree this mapping method needs to be re-examined. Maybe we don't
need it at all because database.csv is already read from elsewhere and
already contains said mappings, at least implicitly so.

**Comment by birkelbach** [comment]
The can-fix mappings need to be separate because it's entirely possible that a person could have multiple CAN-FIX busses that used different offsets.  I'm going to open an issue for this.  There is a bug in there somewhere anyway because this is not the expected behavior.

**Pull request merged**
