### PR TITLE
added persistence of desired FIX entries to hdf5

### PR DESCRIPTION
**Pull request by qubolino**
plugin to be config'ed like this:
```
  db_persister:
    load: yes
    module: fixgw.plugins.db_persister
    db_schema: "database.yaml"
    h5f_file: "../data/db_histo.h5"
    entries_regex: ^(GS|IAS|ALT|HEAD|TRACK|PITCH|ROLL|YAW|ALAT|ALONG|LAT|LONG|TIMEZH|TIMEZM|TIMEZS)$
```
dumping data in a h5 file. can be read in pandas easily through the following snippet:
```
import pandas as pd
df = pd.read_hdf('db_histo.h5', 'ALT')
```
has dependencies to `pytables` and `h5py`

### CODE REVIEW

**Comment by birkelbach** [comment]
Looks good.  I think there may be a better way to get the description than loading the database again.  All that information should already be loaded in FIXGateway.  If there isn't an interface then we should probably add it.  Also this adds the 'tables' module as a dependency.  Not a problem but it needs to be in the install documentation somewhere.

**Comment by qubolino** [comment]
agreed. all your point are valid to me
- i couldn't find a non-intrusive way to get the db desc
- adding the tables was necessary to handle hdf5 files -- tough choice but csv would have been sooo inefficient. could add it as an option though
- essentially you install with `python3 -m pip install tables` although you may face libs missing so in my case (5' screen raspi image) i had to 
```
sudo apt remove python-numpy
sudo apt-get install libatlas-base-dev
sudo apt-get install libhdf5-103```

**Comment by birkelbach** [comment]
We could probably figure out a way to intrude and get a way to read the description.  For now what you have is fine.  I'll look at it later when I have time.  I don't disagree with the decision to use the tables module.  I think it's the right idea, i just wanted to write it down so that we'd know that it was a requirement.  There are plenty of other dependencies, in other plugins.  All in all I think it's great, thanks for taking the time to do that.

**Comment by qubolino** [comment]
well, thank YOU for designing such a flexible framework etc. this tool is truly amazing once you pay the learning curve.

btw i do have a couple of additional plugins, not necessarily sexy, but possibly useful. i will soon commit to my fork and ping you if you want to have a look. won't make pull requests though as i don't think it's mature enough. but may trigger some discussions.

**Comment by birkelbach** [comment]
Sounds good.  I look forward to seeing it.

**Pull request merged**
