### PR TITLE
Added missing CURRENT from MGL RDAC

### PR DESCRIPTION
**Pull request by e100**

### CODE REVIEW

**Comment by EdB987** [comment]
thank you!
I am attempting to exactly duplicate your set up - but will also want to do some dev work - for example, the ADC values returned need to be evaluated by mgl.py for my sensors: VDO Oil temp, electronic oil pressure (.5v - 4.5V 0-100 psi on +5v), mgl current sensor and Sonex CHT generic EGT probes. Still learning how snap works but the readme in Fixgateway was helpful.

**Comment by e100** [comment]
The default config has example of setting gallons to ADC value. 
https://github.com/makerplane/FIX-Gateway/blob/master/fixgw/config/connections/mgl.yaml#L37
Until someone takes the time to make an example calibration for specific sensors you will have to build a calibration table yourself. 
For example to build a calibration table for a temp sensor you could start with putting the sensor in some ice water,  along with a thermometer, then slowly heat the water.  Every 10 degrees you can use the fixgateway client to read the ADC value with command like `read OILT1` to build your table.  The first number in the calibration table would be the temperature from thermometer and the 2nd number is the ADC value that is output from the read command. Once you build the complete table put it into the config file and restart fixgateway. 
Then make a pull request to include your example calibration table,  be sure to specify the sensor part number.  Then someone else who has the same sensor could use the table you created.

**Comment by EdB987** [comment]
That's what I'll do! I have already gotten pretty good calibrations for the sensors mentioned above. My engine is a Great Planes 2273 VW type 1 - I'll only be reading 2 CHTs and 2 EGTs.

**Comment by EdB987** [comment]
by the way - I'll also be incorporating Stratux, but will try to use the Stratux AHRS to avoid yet another board to integrate.

**Comment by EdB987** [comment]
@e100 - I was able to see the Stratux AHRS sensor after initializing the 2nd I2C bus. The X729 and PI RTCs were conflicting. Any pointers on how to write back to fix form sensors.go? Same as what you did, only in reverse.
-OR-
Do you think a better approach would be to write a plugin that simply reads stratux AHRS and writes them to fix and then use your changes to sensors.go?

Another question: did you figure out how to get ap0 and wlan0 to come up automatically? I end up having to ifdown wlan0 and the ifup to make the stratux server visible.

**Comment by EdB987** [comment]
@e100 After some fine tuning, I got most of my setup running. Fixgateway sort of works by listening to Stratux on localhost but the performance of the Stratux AHRS is unsat to say the least after some testing this weekend.  So I'm back to exactly replicating your setup - which I saw you demo on YouTube recently. If it's of interest, the plane I'll be installing pyEfis in is my Sonrai IILS, N988EB ( https://youtu.be/S-f2BhmW0eQ?si=M218ZJmude2C9JVo ). Can we get in touch to learn more about the MAVLINK setup and hardware? I won't be installing any A/P servos however.

**Pull request merged**
